permalink: /:categories/:title.html
url: "http://pasindud.github.io/jekyll-masonry/"
full_name: "Klaus Havelund"
first_name: "Klaus"
last_name: "Havelund"
blog_title: "Homepage"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "havelund"
copyright_year: "2019"
google_analytics_code: ""
aboutme: "Senior Research Scientist"
twitter: "Ghosteyes1"
github: "pasindud"
facebook: "mepasindu"
linkined_url: ""
