import React,{useState} from 'react';
import Link from '@docusaurus/Link';
import Head from '@docusaurus/Head';
import './designs.css';
export default function Designs(){
 const [design,setDesign]=useState('observatory'),[logged,setLogged]=useState(false),[events,setEvents]=useState([]);
 function event(name){const pass=name!=='read_document'||logged;if(name==='login')setLogged(true);if(name==='logout')setLogged(false);setEvents(e=>[...e.slice(-3),{name,pass}]);}
 return <div className={'design-study '+design}><Head><title>Two framed designs | Klaus Havelund</title></Head>
 <div className="study-toolbar"><span>HOMEPAGE DESIGN STUDIES</span><div role="group" aria-label="Choose design"><button aria-pressed={design==='observatory'} onClick={()=>setDesign('observatory')}>01 · Observatory</button><button aria-pressed={design==='workbench'} onClick={()=>setDesign('workbench')}>02 · Workbench</button></div><Link to="/">Current site ↗</Link></div>
 <div className="study-shell"><header className="study-header"><Link to="/designs/" className="study-brand">[ kh ] <span>Klaus Havelund</span></Link><nav aria-label="Website"><Link to="/research/">Research</Link><Link to="/publications/">Publications</Link><Link to="/software/">Software</Link><Link to="/cv/">CV</Link><Link to="/contact/">Contact ↗</Link></nav></header>
 <div className="study-grid"><section className="study-intro framed"><div className="frame-caption"><span>01 / HELLO, WORLD</span><span className="status-dot">●</span></div><div className="intro-body"><p className="study-eyebrow">FORMAL METHODS · RUNTIME VERIFICATION</p><h1>Software.<br/>Space.<br/><em>Confidence.</em></h1><p className="study-lead">I’m Klaus Havelund. I build tools to help us trust the software we depend on.</p><p className="study-affiliation">Senior Research Scientist & Principal<br/>NASA Jet Propulsion Laboratory / Caltech</p><div className="study-actions"><Link to="/publications/">Explore publications ↗</Link><Link to="/research/">Meet the research →</Link></div></div></section>
 <section className="study-monitor framed"><div className="frame-caption"><span>02 / LIVE EXPERIMENT</span><span>● INTERACTIVE</span></div><div className="monitor-body"><p className="study-eyebrow">A SMALL RULE. A REAL VERDICT.</p><h2>Trust, but verify.</h2><p>A document can be read only while logged in. Try reading first—then log in and try again.</p><div className="state-track"><span className={!logged?'state-active':''}>Logged out</span><span>⇄</span><span className={logged?'state-active':''}>Logged in</span></div><div className="study-event-buttons">{['login','read_document','logout'].map(n=><button key={n} onClick={()=>event(n)}>{n}()</button>)}</div><div className="study-log" role="log" aria-live="polite">{events.length?events.map((e,i)=><div key={i}><span>› {e.name}()</span><strong className={e.pass?'ok':'bad'}>{e.pass?'PASS':'VIOLATION'}</strong></div>):<span className="waiting">› Waiting for your first event<span className="cursor">_</span></span>}</div><div className="monitor-foot"><span>STATE: {logged?'AUTHENTICATED':'LOGGED OUT'}</span><button onClick={()=>{setLogged(false);setEvents([]);}}>Reset ↺</button></div></div></section>
 <section className="study-card framed"><div className="frame-caption">03 / RESEARCH</div><h2>Ideas with a specification.</h2><p>Monitoring logics, model checking, and languages that connect mathematical reasoning with working software.</p><Link to="/research/">Research interests →</Link></section>
 <section className="study-card framed"><div className="frame-caption">04 / SOFTWARE</div><h2>Tools you can run.</h2><p>PyContract, DejaVu, TraceContract, and TaskSAT. Putting formal methods to work.</p><Link to="/software/">Explore the tools →</Link></section>
 <section className="study-card study-reading framed"><div className="frame-caption">05 / READING ROOM</div><h2>Follow an idea.</h2><p>Explore publications, or search inside the papers for a topic that interests you.</p><form action="/search/"><label className="sr-only" htmlFor="study-query">Search publications and PDF contents</label><input id="study-query" name="q" placeholder="Try runtime verification…" required/><button aria-label="Search">↗</button></form></section>
 </div><footer className="study-footer"><span>KLAUS HAVELUND / RESEARCH & SOFTWARE</span><span>Stay curious.</span></footer></div></div>;
}
