import React,{useState,useEffect} from 'react';
import Layout from '@theme/Layout';
import {useLocation,useHistory} from '@docusaurus/router';
import Link from '@docusaurus/Link';
import papers from '../../data/publications.json';
import groups from '../../data/publication-groups.json';
import SearchResults from '../components/SearchResults';
import {patterns} from '../lib/search';
export default function Publications(){const location=useLocation(),history=useHistory(),params=new URLSearchParams(location.search),q=params.get('q')||'',full=params.get('scope')==='full';const [value,setValue]=useState(q);useEffect(()=>setValue(q),[q]);function update(text,mode=full){history.replace('/publications?'+new URLSearchParams({q:text,...(mode?{scope:'full'}:{})}));}
 const terms=patterns(q),rows=papers.filter(p=>terms.every(t=>t.test(`${p.title} ${p.authors} ${p.details} ${p.group} ${p.year||''}`.normalize('NFKC').toLowerCase())));
 return <Layout title="Publications"><h1>Publications</h1><p>Search by title, author, topic, or year. Switch to full paper text to search inside the PDFs.</p><nav className="publication-sections" aria-label="Publication sections">{groups.map(g=><a key={g.id} href={'#'+g.id}>{g.title}</a>)}</nav><form className="content-search" onSubmit={e=>{e.preventDefault();update(value);}}><label className="sr-only" htmlFor="paper-query">Search publications</label><input id="paper-query" type="search" value={value} onChange={e=>{setValue(e.target.value);if(!full)update(e.target.value);}} placeholder="Title, author, topic, or year"/><button>Search →</button></form><fieldset className="search-scope"><legend>Search in</legend><label><input type="radio" name="scope" checked={!full} onChange={()=>update(value,false)}/> Titles &amp; authors</label><label><input type="radio" name="scope" checked={full} onChange={()=>update(value,true)}/> Full paper text</label></fieldset>{full?<SearchResults query={q} scope="papers"/>:<><p className="search-status" role="status">{rows.length} entries</p>{groups.map(group=>{const entries=rows.filter(p=>p.group===group.title);if(q&&!entries.length)return null;return <section className="publication-group" id={group.id} key={group.id}><h2>{group.title}</h2>{!q&&group.html?<div className="markdown publication-context" dangerouslySetInnerHTML={{__html:group.html}}/>:entries.map(p=><article className="publication" key={p.id} id={p.id}><p className="year-label">{p.year||'Undated / under review'}</p><h3>{p.title}</h3><p>{p.authors}</p><p>{p.details}</p><div className="paper-links">{p.links.map((l,j)=>l.available===false?<span key={j} title="This file was missing in the original local website">{l.label} (unavailable)</span>:<a key={j} href={l.url}>{l.label} ↗</a>)}</div></article>)}</section>;})}</>}<p><Link to="/cv">Curriculum vitae →</Link></p></Layout>;
}
